using System;
using System.Diagnostics.CodeAnalysis;
using System.Runtime.InteropServices;

namespace LibKenjinx.Jni.Values;

[SuppressMessage("CodeQuality", "IDE0051:Remove unused private members",
                 Justification = "This struct is created only by binary operations.")]
[StructLayout(LayoutKind.Sequential)]
public readonly struct JNativeInterface
{
#pragma warning disable 0169
	private readonly nint _reserved0;
	private readonly nint _reserved1;
	private readonly nint _reserved2;
	private readonly nint _reserved3;
#pragma warning restore 0169
	internal readonly nint GetVersionPointer { get; init; }
	internal readonly nint DefineClassPointer { get; init; }
	internal readonly nint FindClassPointer { get; init; }
	internal readonly nint FromReflectedMethodPointer { get; init; }
	internal readonly nint FromReflectedFieldPointer { get; init; }
	internal readonly nint ToReflectedMethodPointer { get; init; }
	internal readonly nint GetSuperclassPointer { get; init; }
	internal readonly nint IsAssignableFromPointer { get; init; }
	internal readonly nint ToReflectedFieldPointer { get; init; }
	internal readonly nint ThrowPointer { get; init; }
	internal readonly nint ThrowNewPointer { get; init; }
	internal readonly nint ExceptionOccurredPointer { get; init; }
	internal readonly nint ExceptionDescribePointer { get; init; }
	internal readonly nint ExceptionClearPointer { get; init; }
	internal readonly nint FatalErrorPointer { get; init; }
	internal readonly nint PushLocalFramePointer { get; init; }
	internal readonly nint PopLocalFramePointer { get; init; }
	internal readonly nint NewGlobalRefPointer { get; init; }
	internal readonly nint DeleteGlobalRefPointer { get; init; }
	internal readonly nint DeleteLocalRefPointer { get; init; }
	internal readonly nint IsSameObjectPointer { get; init; }
	internal readonly nint NewLocalRefPointer { get; init; }
	internal readonly nint EnsureLocalCapacityPointer { get; init; }
	internal readonly nint AllocObjectPointer { get; init; }
	internal readonly nint NewObjectPointer { get; init; }
	internal readonly nint NewObjectVPointer { get; init; }
	internal readonly nint NewObjectAPointer { get; init; }
	internal readonly nint GetObjectClassPointer { get; init; }
	internal readonly nint IsInstanceOfPointer { get; init; }
	internal readonly nint GetMethodIdPointer { get; init; }
	private readonly nint CallObjectMethodPointer { get; init; }
	private readonly nint CallObjectMethodVPointer { get; init; }
	internal readonly nint CallObjectMethodAPointer { get; init; }
	private readonly nint CallBooleanMethodPointer { get; init; }
	private readonly nint CallBooleanMethodVPointer { get; init; }
	internal readonly nint CallBooleanMethodAPointer { get; init; }
	private readonly nint CallByteMethodPointer { get; init; }
	private readonly nint CallByteMethodVPointer { get; init; }
	internal readonly nint CallByteMethodAPointer { get; init; }
	private readonly nint CallCharMethodPointer { get; init; }
	private readonly nint CallCharMethodVPointer { get; init; }
	internal readonly nint CallCharMethodAPointer { get; init; }
	private readonly nint CallShortMethodPointer { get; init; }
	private readonly nint CallShortMethodVPointer { get; init; }
	internal readonly nint CallShortMethodAPointer { get; init; }
	private readonly nint CallIntMethodPointer { get; init; }
	private readonly nint CallIntMethodVPointer { get; init; }
	internal readonly nint CallIntMethodAPointer { get; init; }
	private readonly nint CallLongMethodPointer { get; init; }
	private readonly nint CallLongMethodVPointer { get; init; }
	internal readonly nint CallLongMethodAPointer { get; init; }
	private readonly nint CallFloatMethodPointer { get; init; }
	private readonly nint CallFloatMethodVPointer { get; init; }
	internal readonly nint CallFloatMethodAPointer { get; init; }
	private readonly nint CallDoubleMethodPointer { get; init; }
	private readonly nint CallDoubleMethodVPointer { get; init; }
	internal readonly nint CallDoubleMethodAPointer { get; init; }
	private readonly nint CallVoidMethodPointer { get; init; }
	private readonly nint CallVoidMethodVPointer { get; init; }
	internal readonly nint CallVoidMethodAPointer { get; init; }
	private readonly nint CallNonVirtualObjectMethodPointer { get; init; }
	private readonly nint CallNonVirtualObjectMethodVPointer { get; init; }
	internal readonly nint CallNonVirtualObjectMethodAPointer { get; init; }
	private readonly nint CallNonVirtualBooleanMethodPointer { get; init; }
	private readonly nint CallNonVirtualBooleanMethodVPointer { get; init; }
	internal readonly nint CallNonVirtualBooleanMethodAPointer { get; init; }
	private readonly nint CallNonVirtualByteMethodPointer { get; init; }
	private readonly nint CallNonVirtualByteMethodVPointer { get; init; }
	internal readonly nint CallNonVirtualByteMethodAPointer { get; init; }
	private readonly nint CallNonVirtualCharMethodPointer { get; init; }
	private readonly nint CallNonVirtualCharMethodVPointer { get; init; }
	internal readonly nint CallNonVirtualCharMethodAPointer { get; init; }
	private readonly nint CallNonVirtualShortMethodPointer { get; init; }
	private readonly nint CallNonVirtualShortMethodVPointer { get; init; }
	internal readonly nint CallNonVirtualShortMethodAPointer { get; init; }
	private readonly nint CallNonVirtualIntMethodPointer { get; init; }
	private readonly nint CallNonVirtualIntMethodVPointer { get; init; }
	internal readonly nint CallNonVirtualIntMethodAPointer { get; init; }
	private readonly nint CallNonVirtualLongMethodPointer { get; init; }
	private readonly nint CallNonVirtualLongMethodVPointer { get; init; }
	internal readonly nint CallNonVirtualLongMethodAPointer { get; init; }
	private readonly nint CallNonVirtualFloatMethodPointer { get; init; }
	private readonly nint CallNonVirtualFloatMethodVPointer { get; init; }
	internal readonly nint CallNonVirtualFloatMethodAPointer { get; init; }
	private readonly nint CallNonVirtualDoubleMethodPointer { get; init; }
	private readonly nint CallNonVirtualDoubleMethodVPointer { get; init; }
	internal readonly nint CallNonVirtualDoubleMethodAPointer { get; init; }
	private readonly nint CallNonVirtualVoidMethodPointer { get; init; }
	private readonly nint CallNonVirtualVoidMethodVPointer { get; init; }
	internal readonly nint CallNonVirtualVoidMethodAPointer { get; init; }
	internal readonly nint GetFieldIdPointer { get; init; }
	internal readonly nint GetObjectFieldPointer { get; init; }
	internal readonly nint GetBooleanFieldPointer { get; init; }
	internal readonly nint GetByteFieldPointer { get; init; }
	internal readonly nint GetCharFieldPointer { get; init; }
	internal readonly nint GetShortFieldPointer { get; init; }
	internal readonly nint GetIntFieldPointer { get; init; }
	internal readonly nint GetLongFieldPointer { get; init; }
	internal readonly nint GetFloatFieldPointer { get; init; }
	internal readonly nint GetDoubleFieldPointer { get; init; }
	internal readonly nint SetObjectFieldPointer { get; init; }
	internal readonly nint SetBooleanFieldPointer { get; init; }
	internal readonly nint SetByteFieldPointer { get; init; }
	internal readonly nint SetCharFieldPointer { get; init; }
	internal readonly nint SetShortFieldPointer { get; init; }
	internal readonly nint SetIntFieldPointer { get; init; }
	internal readonly nint SetLongFieldPointer { get; init; }
	internal readonly nint SetFloatFieldPointer { get; init; }
	internal readonly nint SetDoubleFieldPointer { get; init; }
	internal readonly nint GetStaticMethodIdPointer { get; init; }
	private readonly nint CallStaticObjectMethodPointer { get; init; }
	private readonly nint CallStaticObjectMethodVPointer { get; init; }
	internal readonly nint CallStaticObjectMethodAPointer { get; init; }
	private readonly nint CallStaticBooleanMethodPointer { get; init; }
	private readonly nint CallStaticBooleanMethodVPointer { get; init; }
	internal readonly nint CallStaticBooleanMethodAPointer { get; init; }
	private readonly nint CallStaticByteMethodPointer { get; init; }
	private readonly nint CallStaticByteMethodVPointer { get; init; }
	internal readonly nint CallStaticByteMethodAPointer { get; init; }
	private readonly nint CallStaticCharMethodPointer { get; init; }
	private readonly nint CallStaticCharMethodVPointer { get; init; }
	internal readonly nint CallStaticCharMethodAPointer { get; init; }
	private readonly nint CallStaticShortMethodPointer { get; init; }
	private readonly nint CallStaticShortMethodVPointer { get; init; }
	internal readonly nint CallStaticShortMethodAPointer { get; init; }
	private readonly nint CallStaticIntMethodPointer { get; init; }
	private readonly nint CallStaticIntMethodVPointer { get; init; }
	internal readonly nint CallStaticIntMethodAPointer { get; init; }
	private readonly nint CallStaticLongMethodPointer { get; init; }
	private readonly nint CallStaticLongMethodVPointer { get; init; }
	internal readonly nint CallStaticLongMethodAPointer { get; init; }
	private readonly nint CallStaticFloatMethodPointer { get; init; }
	private readonly nint CallStaticFloatMethodVPointer { get; init; }
	internal readonly nint CallStaticFloatMethodAPointer { get; init; }
	private readonly nint CallStaticDoubleMethodPointer { get; init; }
	private readonly nint CallStaticDoubleMethodVPointer { get; init; }
	internal readonly nint CallStaticDoubleMethodAPointer { get; init; }
	private readonly nint CallStaticVoidMethodPointer { get; init; }
	private readonly nint CallStaticVoidMethodVPointer { get; init; }
	internal readonly nint CallStaticVoidMethodAPointer { get; init; }
	internal readonly nint GetStaticFieldIdPointer { get; init; }
	internal readonly nint GetStaticObjectFieldPointer { get; init; }
	internal readonly nint GetStaticBooleanFieldPointer { get; init; }
	internal readonly nint GetStaticByteFieldPointer { get; init; }
	internal readonly nint GetStaticCharFieldPointer { get; init; }
	internal readonly nint GetStaticShortFieldPointer { get; init; }
	internal readonly nint GetStaticIntFieldPointer { get; init; }
	internal readonly nint GetStaticLongFieldPointer { get; init; }
	internal readonly nint GetStaticFloatFieldPointer { get; init; }
	internal readonly nint GetStaticDoubleFieldPointer { get; init; }
	internal readonly nint SetStaticObjectFieldPointer { get; init; }
	internal readonly nint SetStaticBooleanFieldPointer { get; init; }
	internal readonly nint SetStaticByteFieldPointer { get; init; }
	internal readonly nint SetStaticCharFieldPointer { get; init; }
	internal readonly nint SetStaticShortFieldPointer { get; init; }
	internal readonly nint SetStaticIntFieldPointer { get; init; }
	internal readonly nint SetStaticLongFieldPointer { get; init; }
	internal readonly nint SetStaticFloatFieldPointer { get; init; }
	internal readonly nint SetStaticDoubleFieldPointer { get; init; }
	internal readonly nint NewStringPointer { get; init; }
	internal readonly nint GetStringLengthPointer { get; init; }
	internal readonly nint GetStringCharsPointer { get; init; }
	internal readonly nint ReleaseStringCharsPointer { get; init; }
	internal readonly nint NewStringUtfPointer { get; init; }
	internal readonly nint GetStringUtfLengthPointer { get; init; }
	internal readonly nint GetStringUtfCharsPointer { get; init; }
	internal readonly nint ReleaseStringUtfCharsPointer { get; init; }
	internal readonly nint GetArrayLengthPointer { get; init; }
	internal readonly nint NewObjectArrayPointer { get; init; }
	internal readonly nint GetObjectArrayElementPointer { get; init; }
	internal readonly nint SetObjectArrayElementPointer { get; init; }
	internal readonly nint NewBooleanArrayPointer { get; init; }
	internal readonly nint NewByteArrayPointer { get; init; }
	internal readonly nint NewCharArrayPointer { get; init; }
	internal readonly nint NewShortArrayPointer { get; init; }
	internal readonly nint NewIntArrayPointer { get; init; }
	internal readonly nint NewLongArrayPointer { get; init; }
	internal readonly nint NewFloatArrayPointer { get; init; }
	internal readonly nint NewDoubleArrayPointer { get; init; }
	internal readonly nint GetBooleanArrayElementsPointer { get; init; }
	internal readonly nint GetByteArrayElementsPointer { get; init; }
	internal readonly nint GetCharArrayElementsPointer { get; init; }
	internal readonly nint GetShortArrayElementsPointer { get; init; }
	internal readonly nint GetIntArrayElementsPointer { get; init; }
	internal readonly nint GetLongArrayElementsPointer { get; init; }
	internal readonly nint GetFloatArrayElementsPointer { get; init; }
	internal readonly nint GetDoubleArrayElementsPointer { get; init; }
	internal readonly nint ReleaseBooleanArrayElementsPointer { get; init; }
	internal readonly nint ReleaseByteArrayElementsPointer { get; init; }
	internal readonly nint ReleaseCharArrayElementsPointer { get; init; }
	internal readonly nint ReleaseShortArrayElementsPointer { get; init; }
	internal readonly nint ReleaseIntArrayElementsPointer { get; init; }
	internal readonly nint ReleaseLongArrayElementsPointer { get; init; }
	internal readonly nint ReleaseFloatArrayElementsPointer { get; init; }
	internal readonly nint ReleaseDoubleArrayElementsPointer { get; init; }
	internal readonly nint GetBooleanArrayRegionPointer { get; init; }
	internal readonly nint GetByteArrayRegionPointer { get; init; }
	internal readonly nint GetCharArrayRegionPointer { get; init; }
	internal readonly nint GetShortArrayRegionPointer { get; init; }
	internal readonly nint GetIntArrayRegionPointer { get; init; }
	internal readonly nint GetLongArrayRegionPointer { get; init; }
	internal readonly nint GetFloatArrayRegionPointer { get; init; }
	internal readonly nint GetDoubleArrayRegionPointer { get; init; }
	internal readonly nint SetBooleanArrayRegionPointer { get; init; }
	internal readonly nint SetByteArrayRegionPointer { get; init; }
	internal readonly nint SetCharArrayRegionPointer { get; init; }
	internal readonly nint SetShortArrayRegionPointer { get; init; }
	internal readonly nint SetIntArrayRegionPointer { get; init; }
	internal readonly nint SetLongArrayRegionPointer { get; init; }
	internal readonly nint SetFloatArrayRegionPointer { get; init; }
	internal readonly nint SetDoubleArrayRegionPointer { get; init; }
	internal readonly nint RegisterNativesPointer { get; init; }
	internal readonly nint UnregisterNativesPointer { get; init; }
	internal readonly nint MonitorEnterPointer { get; init; }
	internal readonly nint MonitorExitPointer { get; init; }
	internal readonly nint GetJavaVMPointer { get; init; }
	internal readonly nint GetStringRegionPointer { get; init; }
	internal readonly nint GetStringUtfRegionPointer { get; init; }
	internal readonly nint GetPrimitiveArrayCriticalPointer { get; init; }
	internal readonly nint ReleasePrimitiveArrayCriticalPointer { get; init; }
	internal readonly nint GetStringCriticalPointer { get; init; }
	internal readonly nint ReleaseStringCriticalPointer { get; init; }
	internal readonly nint NewWeakGlobalRefPointer { get; init; }
	internal readonly nint DeleteWeakGlobalRefPointer { get; init; }
	internal readonly nint ExceptionCheckPointer { get; init; }
	internal readonly nint NewDirectByteBufferPointer { get; init; }
	internal readonly nint GetDirectBufferAddressPointer { get; init; }
	internal readonly nint GetDirectBufferCapacityPointer { get; init; }
	internal readonly nint GetObjectRefTypePointer { get; init; }
}
